name: changesets-snapshot-release
description: A GitHub action to automate snapshot releases with Changesets
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  publish:
    description: "The command to use to build and publish packages"
    required: true
  version:
    description: "The command to update version, edit CHANGELOG, read and delete changesets"
    required: true
  cwd:
    description: Sets the cwd for the node process. Default to `process.cwd()`
    required: false
outputs:
  published:
    description: A boolean value to indicate whether a publishing is happened or not
  published-packages:
    description: >
      A JSON array to present the published packages. The format is `[{"name": "@xx/xx", "version": "1.2.0"}, {"name": "@xx/xy", "version": "0.8.9"}]`
