name: setup ci

runs:
  using: composite
  steps:
    - id: detect
      shell: bash
      run: |
        NODE_VERSION_FILE=.node-version
        NODE_VERSION=22

        if [ -f $NODE_VERSION_FILE ]; then
            NODE_VERSION="$(cat $NODE_VERSION_FILE)"
        fi

        echo "node-version=$NODE_VERSION" >> "$GITHUB_OUTPUT"

    - name: setup nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.detect.outputs.node-version }}
        cache: npm

    - name: install dependencies
      shell: bash
      run: |
        npm install
